import React, { useCallback, useState, useEffect } from 'react'
import { FaPlus, FaTrash } from "react-icons/fa6";
import { GoPeople, GoGraph } from "react-icons/go";
import { TiFlashOutline, TiTickOutline } from "react-icons/ti";
import { useNavigate } from 'react-router-dom'
import api from '../../utils/api';
import { IconType } from 'react-icons';
import { auth } from '../../utils/auth';

// ─── Per-category accent tones (mirrors IntegrationsPage palette) ──────────────
const CATEGORY_TONES: Record<string, { shadow: string; logoBg: string; headerBg: string }> = {
  ping_federate:  { shadow: 'rgba(233,71,42,0.15)',  logoBg: '#FFF5F3', headerBg: '#FFF8F7' },
  ping_directory: { shadow: 'rgba(10,133,194,0.15)', logoBg: '#F0F8FF', headerBg: '#F5FBFF' },
  ping_one:       { shadow: 'rgba(124,58,237,0.15)', logoBg: '#FAF5FF', headerBg: '#FCF9FF' },
  unknown:        { shadow: 'rgba(107,114,128,0.15)',logoBg: '#F9FAFB', headerBg: '#FAFAFA' },
};

// ── Local avatar manifest (generated by scripts/downloadHeyGenAvatars.ts) ──
// Maps avatar_id → local path like /avatars/Marianne_ProfessionalLook_public.webp
let avatarManifest: Record<string, string> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  avatarManifest = require('../../data/avatarManifest.json');
} catch {
  // Script not run yet — will fall back to stored CDN URL or initials
}

/**
 * Resolve the best image URL for an avatar:
 * 1. Local cached file from manifest (fastest, no CORS)
 * 2. Stored img URL from agent config (CDN — may have CORS issues)
 * 3. Empty string → AvatarPhoto shows initials
 */
function resolveAvatarImg(avatarId: string, storedImg: string): string {
  if (avatarId && avatarManifest[avatarId]) return avatarManifest[avatarId];
  if (storedImg && !storedImg.match(/\.(mp4|webm|mov)(\?|$)/i)) return storedImg;
  return '';
}

interface Agent {
  id: string;
  name: string;
  role: string;
  type: string;
  avatarImg: string;
  avatarName: string;
  avatarId: string;        // ← needed for manifest lookup
  tasks: string;
  success: string;
  status: string;
  environment?: string;
  isDefault: boolean;
  killswitchActivated?: boolean;
  category: string;
}

interface StatData { icon: IconType; value: string; description: string; sub: string; iconcolor: string; bg: string; }

interface TargetSystem { id?: string; _id?: string; type: string; }

interface RemoteAgent {
  id: string; name: string; type: string; description?: string;
  checkInterval?: number; status?: string;
  config?: {
    environment?: string;
    integrationType?: string;      // ← stored at creation time, most reliable for category
    targetSystemName?: string;
    selectedAvatarId?: string;
    selectedAvatarImg?: string;
    selectedAvatarName?: string;
  };
  killswitch_activated?: boolean;
}

interface AgentMetrics {
  agent_id: string;
  total_tasks: number;
  successful_tasks: number;
  failed_tasks: number;
  overall_success_rate: number;
  avg_response_time_ms: number;
  min_response_time_ms: number;
  max_response_time_ms: number;
}

interface DailyMetrics {
  date: string;
  total_tasks: number;
  successful_tasks: number;
  failed_tasks: number;
}

interface DashboardMetricsResponse {
  daily_metrics_past_7_days: DailyMetrics[];
  agent_metrics: AgentMetrics[];
  timestamp: string;
}

interface TargetSystemMap { [key: string]: string; }

const CATEGORY_CONFIG: Record<string, { label: string; accent: string; tagline: string; icon: string }> = {
  ping_federate:  { label: 'PingFederate',  accent: '#E9472A', tagline: 'Federation & SSO Agents',  icon: '🔐' },
  ping_directory: { label: 'PingDirectory', accent: '#0A85C2', tagline: 'Directory & LDAP Agents',  icon: '📁' },
  ping_one:       { label: 'PingOne',       accent: '#7C3AED', tagline: 'Cloud Identity Agents',    icon: '☁️' },
  unknown:        { label: 'Other Agents',  accent: '#6B7280', tagline: 'Miscellaneous Agents',     icon: '🤖' },
};

const resolveCategory = (input: string): string => {
  if (!input) return 'unknown';
  const t = input.toLowerCase().replace(/[-\s]/g, '_');
  // Match PingFederate variants: ping_federate, pingfederate, ping federate
  if (t.includes('ping_federate') || t.includes('pingfederate') || t.includes('federation')) return 'ping_federate';
  // Match PingDirectory variants
  if (t.includes('ping_directory') || t.includes('pingdirectory') || t.includes('directory')) return 'ping_directory';
  // Match PingOne variants
  if (t.includes('ping_one') || t.includes('pingone')) return 'ping_one';
  return 'unknown';
};

// ─── Avatar photo with graceful initials fallback ─────────────────────────────
interface AvatarPhotoProps {
  src: string;
  name: string;
  size: number;
  accent?: string;
  className?: string;
  style?: React.CSSProperties;
}
const AvatarPhoto: React.FC<AvatarPhotoProps> = ({ src, name, size, accent = '#6366f1', className = '', style = {} }) => {
  const [imgSrc, setImgSrc] = useState(src);
  const [failed, setFailed] = useState(false);

  // Reset when src changes (e.g. agent data loads)
  useEffect(() => { setImgSrc(src); setFailed(false); }, [src]);

  const initial = (name?.[0] ?? '?').toUpperCase();

  if (!imgSrc || failed) {
    return (
      <div
        className={`flex items-center justify-center text-white font-bold rounded-full flex-shrink-0 ${className}`}
        style={{
          width: size, height: size, fontSize: size * 0.38,
          background: `linear-gradient(135deg, ${accent}cc, ${accent})`,
          ...style,
        }}
      >
        {initial}
      </div>
    );
  }
  return (
    <img
      src={imgSrc}
      alt={name}
      className={`object-cover object-top rounded-full flex-shrink-0 ${className}`}
      style={{ width: size, height: size, ...style }}
      onError={() => setFailed(true)}
    />
  );
};

// ─── Agent Card ───────────────────────────────────────────────────────────────
interface AgentCardProps {
  agent: Agent;
  accent: string;
  category: string;
  metrics?: AgentMetrics | null;
  onDelete: (e: React.MouseEvent<HTMLButtonElement>, agent: Agent) => void;
  onClick: () => void;
}

const AgentCard: React.FC<AgentCardProps> = ({ agent, accent, category, metrics, onDelete, onClick }) => {
  const [hovered, setHovered] = useState(false);
  const isKilled = agent.killswitchActivated;
  const isActive = agent.status === 'active' && !isKilled;
  const resolvedImg = resolveAvatarImg(agent.avatarId, agent.avatarImg);
  const tones = CATEGORY_TONES[category] || CATEGORY_TONES.unknown;

  const cardStyle: React.CSSProperties = hovered && !isKilled ? {
    borderColor: accent,
    boxShadow: `0 4px 6px -1px rgba(0,0,0,0.04), 0 20px 40px -8px ${tones.shadow}`,
    transform: 'translateY(-3px)',
  } : {};

  return (
    <div
      className="agent-card bg-white border border-gray-200 rounded-2xl overflow-hidden cursor-pointer transition-all duration-[220ms] flex flex-col relative"
      style={isKilled ? { opacity: 0.5, border: '1px solid #e5e7eb' } : cardStyle}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      onClick={!isKilled ? onClick : undefined}
    >
      {/* Top accent bar */}
      <div
        className="agent-accent-bar"
        style={{ background: accent }}
      />

      {/* Avatar zone */}
      <div
        className="flex items-center justify-center border-b border-gray-100 min-h-[160px] px-7 py-8 transition-colors duration-200 relative"
        style={{ background: hovered && !isKilled ? tones.headerBg : '#FAFAFA' }}
      >
        {/* Delete button */}
        <button
          onClick={(e) => onDelete(e, agent)}
          title="Delete agent"
          className="absolute top-3 left-3 z-10 w-7 h-7 flex items-center justify-center rounded-full bg-white shadow-md border border-gray-100 text-gray-400 hover:text-red-600 hover:border-red-200 hover:bg-red-50 transition-all duration-200 opacity-0 group-hover:opacity-100 agent-delete-btn"
        >
          <FaTrash size={11} />
        </button>

        {/* Avatar */}
        <div
          className="w-[100px] h-[100px] rounded-full p-[3px] transition-all duration-200"
          style={{
            background: hovered && !isKilled
              ? `linear-gradient(135deg, ${accent}88, ${accent})`
              : 'linear-gradient(135deg, #e5e7eb, #d1d5db)',
            boxShadow: hovered && !isKilled ? `0 4px 16px ${accent}40` : 'none',
          }}
        >
          <div className="w-full h-full rounded-full overflow-hidden" style={{ background: tones.logoBg }}>
            <AvatarPhoto
              src={resolvedImg}
              name={agent.avatarName || agent.name}
              size={94}
              accent={accent}
              className={`w-full h-full ${isKilled ? 'grayscale' : ''}`}
              style={{ width: '100%', height: '100%' }}
            />
          </div>
        </div>
      </div>

      {/* Body */}
      <div className="px-6 pt-5 pb-6 flex-1 flex flex-col gap-3">
        {/* Name + status row */}
        <div className="flex flex-col gap-1">
          <div className="flex items-center justify-between gap-2">
            <span className="text-[15px] font-semibold text-[#0A0A0A] tracking-tight leading-tight">
              {agent.name}
            </span>
            <span
              className={`flex items-center gap-1 px-2 py-0.5 rounded-full text-[10.5px] font-semibold whitespace-nowrap flex-shrink-0 border
                ${isActive
                  ? 'bg-green-50 border-green-200 text-green-700'
                  : isKilled
                    ? 'bg-gray-50 border-gray-200 text-gray-400'
                    : 'bg-amber-50 border-amber-200 text-amber-700'}`}
            >
              <span className={`agent-status-dot w-1.5 h-1.5 rounded-full inline-block
                ${isActive ? 'bg-green-400' : isKilled ? 'bg-gray-300' : 'bg-amber-400'}`}
              />
              {isActive ? 'Active' : isKilled ? 'Disabled' : 'Inactive'}
            </span>
          </div>
          <p className="text-[12.5px] text-gray-500 leading-relaxed font-normal m-0">
            {agent.role}
          </p>
        </div>

        {/* Badges */}
        <div className="flex flex-wrap gap-1.5 mt-auto">
          <span
            className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[11px] font-medium whitespace-nowrap"
            style={{ background: `${accent}18`, color: accent }}
          >
            <span className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: accent }} />
            {agent.type}
          </span>
          {agent.environment && (
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-[11px] font-medium whitespace-nowrap bg-gray-100 text-gray-500">
              <span className="w-1.5 h-1.5 rounded-full bg-gray-400 flex-shrink-0" />
              {agent.environment}
            </span>
          )}
        </div>
      </div>

      {/* Footer */}
      <div className="border-t border-gray-100 px-6 py-3 flex items-center justify-between">
        <div className="flex gap-5">
          <div className="text-center">
            <div className="text-[13px] font-bold text-[#0A0A0A]">{metrics?.total_tasks ?? 0}</div>
            <div className="text-[10px] text-gray-400 leading-tight">Tasks</div>
          </div>
          <div className="text-center">
            <div className="text-[13px] font-bold text-emerald-600">
              {metrics?.overall_success_rate != null
                ? `${Math.round(metrics.overall_success_rate)}%`
                : agent.success}
            </div>
            <div className="text-[10px] text-gray-400 leading-tight">Success</div>
          </div>
        </div>

        {/* Arrow */}
        <div
          className="w-7 h-7 rounded-lg border border-gray-200 flex items-center justify-center text-[13px] transition-all duration-150"
          style={
            hovered && !isKilled
              ? { background: accent, borderColor: accent, color: '#fff', transform: 'translateX(2px)' }
              : { background: '#fff', color: '#9CA3AF' }
          }
        >
          →
        </div>
      </div>
    </div>
  );
};

// ─── Category Section ─────────────────────────────────────────────────────────
interface CategorySectionProps {
  categoryKey: string;
  agents: Agent[];
  telemetryData: DashboardMetricsResponse | null;
  onDelete: (e: React.MouseEvent<HTMLButtonElement>, agent: Agent) => void;
  onNavigate: (agent: Agent) => void;
}

const CategorySection: React.FC<CategorySectionProps> = ({ categoryKey, agents, telemetryData, onDelete, onNavigate }) => {
  const config = CATEGORY_CONFIG[categoryKey] || CATEGORY_CONFIG.unknown;
  return (
    <div className="mb-12">
      {/* Category header — mirrors IntegrationsPage section style */}
      <div className="flex items-center gap-3 mb-6">
        <div
          className="w-10 h-10 rounded-xl flex items-center justify-center text-lg flex-shrink-0"
          style={{ background: `${config.accent}18` }}
        >
          {config.icon}
        </div>
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-[#0A0A0A]">{config.label}</h2>
            <span
              className="text-[11px] font-semibold px-2 py-0.5 rounded-md"
              style={{ background: `${config.accent}18`, color: config.accent }}
            >
              {agents.length} agent{agents.length !== 1 ? 's' : ''}
            </span>
          </div>
          <p className="text-[12px] text-gray-400 mt-0.5">{config.tagline}</p>
        </div>
        {/* Fading accent divider */}
        <div className="flex-1 h-px ml-1" style={{ background: `linear-gradient(to right, ${config.accent}30, transparent)` }} />
      </div>

      <div className="grid gap-5" style={{ gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))' }}>
        {agents.map((agent, i) => {
          const agentMetrics = telemetryData?.agent_metrics?.length
            ? telemetryData.agent_metrics.find(m => m.agent_id === agent.id)
            : null;
          return (
            <AgentCard
              key={agent.id || i}
              agent={agent}
              accent={config.accent}
              category={categoryKey}
              metrics={agentMetrics ?? null}
              onDelete={onDelete}
              onClick={() => { if (!agent.killswitchActivated) onNavigate(agent); }}
            />
          );
        })}
      </div>
    </div>
  );
};

// ─── Main Page ────────────────────────────────────────────────────────────────
const Agents: React.FC = () => {
  const navigate = useNavigate();
  const [agents,          setAgents]          = useState<Agent[]>([]);
  const [loading,         setLoading]         = useState<boolean>(true);
  const [error,           setError]           = useState<string>('');
  const [showDeleteModal, setShowDeleteModal] = useState<boolean>(false);
  const [agentToDelete,   setAgentToDelete]   = useState<Agent | null>(null);
  const [activeFilter,    setActiveFilter]    = useState<string>('All');
  const [telemetryData,   setTelemetryData]   = useState<DashboardMetricsResponse | null>(null);

  useEffect(() => {
    const formatSystemTypeName = (systemType: string): string => {
      if (!systemType) return 'System';
      return systemType.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
    };

    const fetchAgents = async (): Promise<void> => {
      try {
        let targetSystemMap: TargetSystemMap = {};
        try {
          const targetSystems: TargetSystem[] = await api.targetSystems.list();
          if (Array.isArray(targetSystems)) {
            targetSystems.forEach(system => {
              const systemId = system.id || system._id;
              if (systemId) targetSystemMap[systemId] = system.type;
            });
          }
        } catch (err) { console.warn('Failed to fetch target systems:', err); }

        const remoteAgents: RemoteAgent[] = await api.llmRuntime.listAgents();
        const normalized: Agent[] = (remoteAgents || []).map(agent => {
          let systemType = agent.type;
          const targetMatch = (agent.description || '').match(/\(target\s+([a-f0-9\-]+)\)/);
          if (targetMatch) {
            const tid = targetMatch[1];
            if (targetSystemMap[tid]) systemType = targetSystemMap[tid];
          }

          const avatarId  = agent.config?.selectedAvatarId  ?? '';
          const storedImg = agent.config?.selectedAvatarImg  ?? '';

          // Category resolution priority:
          // 1. integrationType stored in config at creation time (most reliable)
          // 2. targetSystemMap lookup via description regex (requires API)
          // 3. targetSystemName from config (human-readable, e.g. "PingFederate Dev")
          // 4. agent.type as last resort
          const storedIntegrationType = agent.config?.integrationType ?? '';
          const targetSystemName      = agent.config?.targetSystemName ?? '';

          const categoryInput =
            storedIntegrationType                      ? storedIntegrationType :
            systemType !== agent.type                  ? systemType :
            targetSystemName                           ? targetSystemName :
            agent.type;

          const role = `${formatSystemTypeName(
            storedIntegrationType || (systemType !== agent.type ? systemType : agent.type)
          )} Agent`;

          return {
            id:                  agent.id,
            name:                agent.name,
            role,
            type:                agent.type,
            avatarId,
            avatarImg:           storedImg,
            avatarName:          agent.config?.selectedAvatarName ?? '',
            tasks:               agent.checkInterval ? Math.max(1, Math.floor(86400 / agent.checkInterval)).toString() : '0',
            success:             agent.status === 'active' ? '100%' : '0%',
            status:              agent.status || 'active',
            environment:         agent.config?.environment,
            isDefault:           false,
            killswitchActivated: agent.killswitch_activated || false,
            category:            resolveCategory(categoryInput),
          };
        });

        setAgents(normalized);
      } catch (err) {
        console.error('Failed to fetch agents', err);
        setError('Unable to load agents from runtime');
        setAgents([]);
      } finally { setLoading(false); }
    };

    fetchAgents();
  }, []);

  // ─── Fetch telemetry ───────────────────────────────────────────────────────
  useEffect(() => {
    const fetchTelemetry = async (): Promise<void> => {
      try {
        const token = auth.getToken();
        if (!token) return;
        const response = await fetch('/api/v1/telemetry/dashboard?days=7', {
          headers: { 'Authorization': `Bearer ${token}`, 'Content-Type': 'application/json' }
        });
        if (response.ok) setTelemetryData(await response.json());
      } catch (error: any) { console.error('Error fetching telemetry:', error); }
    };
    fetchTelemetry();
  }, []);

  const handleCreateAgent = useCallback(() => navigate('/agents/select-target'), [navigate]);

  const alive   = agents.filter(a => !a.killswitchActivated);
  const active  = agents.filter(a => a.status === 'active' && !a.killswitchActivated);

  const totalTasks = telemetryData?.agent_metrics?.length
    ? telemetryData.agent_metrics.filter(m => alive.some(a => a.id === m.agent_id)).reduce((s, m) => s + m.total_tasks, 0)
    : alive.reduce((s, a) => s + parseInt(a.tasks || '0'), 0);

  const relevantMetrics = telemetryData?.agent_metrics?.filter(m => alive.some(a => a.id === m.agent_id)) ?? [];
  const avgSuccessRate  = relevantMetrics.length
    ? (relevantMetrics.reduce((s, m) => s + m.overall_success_rate, 0) / relevantMetrics.length).toFixed(1)
    : '0.0';

  const stats: StatData[] = [
    { icon: GoPeople,       value: alive.length.toString(),  description: 'Total Agents',     sub: '+1 this month',     iconcolor: '#60A5FA', bg: '#EFF6FF' },
    { icon: TiFlashOutline, value: active.length.toString(), description: 'Active Now',       sub: '75% uptime',        iconcolor: '#22C55E', bg: '#F0FDF4' },
    { icon: TiTickOutline,  value: totalTasks.toString(),    description: 'Tasks Completed',  sub: '+12% vs last week', iconcolor: '#A78BFA', bg: '#F5F3FF' },
    { icon: GoGraph,        value: `${avgSuccessRate}%`,     description: 'Avg Success Rate', sub: '+2.3% improvement', iconcolor: '#F97316', bg: '#FFF7ED' },
  ];

  const filters = ['All', 'Production', 'Staging', 'Development', 'Inactive'];

  const getFilteredAgents = (): Agent[] => {
    switch (activeFilter) {
      case 'Production':  return agents.filter(a => !a.killswitchActivated && ['production', 'prod'].includes(a.environment?.toLowerCase() || ''));
      case 'Staging':     return agents.filter(a => !a.killswitchActivated && ['staging', 'stage'].includes(a.environment?.toLowerCase() || ''));
      case 'Development': return agents.filter(a => !a.killswitchActivated && ['development', 'dev'].includes(a.environment?.toLowerCase() || ''));
      case 'Inactive':    return agents.filter(a => a.killswitchActivated || a.status !== 'active');
      default:            return agents.filter(a => !a.killswitchActivated);
    }
  };

  const filteredAgents  = getFilteredAgents();
  const categoryOrder   = ['ping_federate', 'ping_directory', 'ping_one', 'unknown'];
  const grouped: Record<string, Agent[]> = {};
  categoryOrder.forEach(k => { grouped[k] = []; });
  filteredAgents.forEach(a => { if (!grouped[a.category]) grouped[a.category] = []; grouped[a.category].push(a); });
  const activeCategories = categoryOrder.filter(k => grouped[k]?.length > 0);

  const handleDeleteClick = useCallback((e: React.MouseEvent<HTMLButtonElement>, agent: Agent) => {
    e.stopPropagation(); setAgentToDelete(agent); setShowDeleteModal(true);
  }, []);

  const confirmDelete = useCallback(() => {
    if (!agentToDelete) return;
    (async () => {
      try {
        await api.llmRuntime.deleteAgent(agentToDelete.id);
        setAgents(prev => prev.filter(a => a.id !== agentToDelete.id));
      } catch (err: any) { alert('Failed to delete agent: ' + err.message); }
      finally { setShowDeleteModal(false); setAgentToDelete(null); }
    })();
  }, [agentToDelete]);

  const cancelDelete = useCallback(() => { setShowDeleteModal(false); setAgentToDelete(null); }, []);

  return (
    <>
      {/* ── DM Sans font + card animations matching IntegrationsPage ── */}
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,300&display=swap');

        .agents-font { font-family: 'DM Sans', sans-serif; }

        /* Card rise animation */
        @keyframes agent-rise {
          from { opacity: 0; transform: translateY(16px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .agent-card { animation: agent-rise 0.4s ease both; }
        .agent-card:nth-child(1)  { animation-delay: 0.03s; }
        .agent-card:nth-child(2)  { animation-delay: 0.06s; }
        .agent-card:nth-child(3)  { animation-delay: 0.09s; }
        .agent-card:nth-child(4)  { animation-delay: 0.12s; }
        .agent-card:nth-child(5)  { animation-delay: 0.15s; }
        .agent-card:nth-child(6)  { animation-delay: 0.18s; }
        .agent-card:nth-child(7)  { animation-delay: 0.21s; }
        .agent-card:nth-child(8)  { animation-delay: 0.24s; }
        .agent-card:nth-child(9)  { animation-delay: 0.27s; }
        .agent-card:nth-child(10) { animation-delay: 0.30s; }
        .agent-card:nth-child(11) { animation-delay: 0.33s; }
        .agent-card:nth-child(12) { animation-delay: 0.36s; }

        /* Accent bar: scaleX on hover */
        .agent-accent-bar {
          height: 3px;
          transform: scaleX(0);
          transform-origin: left;
          transition: transform 0.3s ease;
        }
        .agent-card:hover .agent-accent-bar { transform: scaleX(1); }

        /* Delete button visible on card hover */
        .agent-card:hover .agent-delete-btn { opacity: 1 !important; }

        /* Pulsing status dot */
        @keyframes agent-pulse {
          0%, 100% { opacity: 1; }
          50%       { opacity: 0.4; }
        }
        .agent-status-dot { animation: agent-pulse 2s ease infinite; }
      `}</style>

      <div className="agents-font min-h-screen bg-[#FAFAFA] text-[#111]">

        {/* Delete modal */}
        {showDeleteModal && (
          <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-8">
              <div className="flex justify-center mb-6">
                <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center">
                  <FaTrash className="text-red-600 text-2xl" />
                </div>
              </div>
              <h2 className="text-2xl font-bold text-[#0A0A0A] text-center mb-3">Delete Agent?</h2>
              {agentToDelete && (
                <div className="bg-gray-50 rounded-xl p-4 mb-6 flex items-center gap-3">
                  <AvatarPhoto
                    src={resolveAvatarImg(agentToDelete.avatarId, agentToDelete.avatarImg)}
                    name={agentToDelete.avatarName || agentToDelete.name}
                    size={48}
                    className="flex-shrink-0"
                  />
                  <div>
                    <p className="font-semibold text-[#0A0A0A]">{agentToDelete.name}</p>
                    <p className="text-sm text-gray-500">{agentToDelete.role}</p>
                    {agentToDelete.environment && (
                      <p className="text-xs text-gray-400 mt-1">Env: {agentToDelete.environment}</p>
                    )}
                  </div>
                </div>
              )}
              <p className="text-gray-500 text-center mb-8 text-sm">
                This action cannot be undone. All monitoring for this agent will stop.
              </p>
              <div className="flex gap-3">
                <button onClick={cancelDelete}
                  className="flex-1 px-6 py-3 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-xl font-medium text-sm transition-colors">
                  Cancel
                </button>
                <button onClick={confirmDelete}
                  className="flex-1 px-6 py-3 bg-red-600 hover:bg-red-700 text-white rounded-xl font-medium text-sm transition-colors">
                  Yes, Delete
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ── Header ── */}
        <div className="bg-white border-b border-gray-200 px-12 max-md:px-5">
          <div className="max-w-[1400px] mx-auto pt-10 pb-8">
            <h1 className="text-4xl font-bold leading-tight tracking-tight text-[#0A0A0A] mb-2 max-md:text-3xl">
              AI Agents
            </h1>
            <p className="text-[15px] text-gray-500 font-normal max-w-[480px] leading-relaxed m-0">
              Manage and monitor your AI-powered IAM agents
            </p>
          </div>
        </div>

        {/* ── Sticky Toolbar ── */}
        <div className="bg-white border-b border-gray-200 px-12 sticky top-0 z-20 max-md:px-5">
          <div className="max-w-[1400px] mx-auto flex items-center justify-between gap-6 h-14">
            {/* Filter pills */}
            <div className="flex items-center gap-0.5">
              {filters.map(f => (
                <button
                  key={f}
                  onClick={() => setActiveFilter(f)}
                  className={`px-3.5 py-1.5 rounded-md border-none text-[13px] font-medium cursor-pointer transition-all duration-150 whitespace-nowrap font-[inherit]
                    ${activeFilter === f
                      ? 'bg-[#111] text-white'
                      : 'bg-transparent text-gray-500 hover:bg-gray-100 hover:text-[#111]'}`}
                >
                  {f}
                </button>
              ))}
            </div>
            <div className="flex items-center gap-3">
              <span className="text-[13px] text-gray-400 whitespace-nowrap font-normal">
                {filteredAgents.length} agent{filteredAgents.length !== 1 ? 's' : ''}
              </span>
              <button
                onClick={handleCreateAgent}
                className="bg-[#111] hover:bg-[#333] text-white px-4 h-8 rounded-lg flex items-center gap-1.5 text-[13px] font-medium transition-colors"
              >
                <FaPlus size={11} /> New Agent
              </button>
            </div>
          </div>
        </div>

        {/* ── Stats strip ── */}
        <div className="bg-white border-b border-gray-100 px-12 max-md:px-5">
          <div className="max-w-[1400px] mx-auto py-4">
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
              {stats.map((s, i) => {
                const Icon = s.icon;
                return (
                  <div key={i} className="flex items-center gap-3 bg-gray-50 rounded-xl p-4 border border-gray-100">
                    <div className="w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0" style={{ background: s.bg }}>
                      <Icon style={{ color: s.iconcolor }} size={17} />
                    </div>
                    <div>
                      <div className="text-xl font-bold text-[#0A0A0A]">{s.value}</div>
                      <div className="text-[11px] text-gray-400 mt-0.5">{s.description}</div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* ── Content ── */}
        <div className="max-w-[1400px] mx-auto px-12 pt-10 pb-20 max-md:px-5 max-md:pt-6 max-md:pb-16">
          {loading ? (
            <div className="flex items-center justify-center py-24">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-[#111]" />
            </div>
          ) : error ? (
            <div className="bg-red-50 border border-red-200 rounded-xl p-6 text-red-600 text-sm">{error}</div>
          ) : filteredAgents.length === 0 ? (
            <div className="bg-white rounded-2xl border border-gray-200 p-16 text-center">
              <div className="text-5xl mb-4 opacity-40">🤖</div>
              <p className="text-gray-500 text-lg font-medium">
                {activeFilter === 'All' ? 'No agents configured yet.' : `No ${activeFilter.toLowerCase()} agents found.`}
              </p>
              {activeFilter === 'All' && (
                <button onClick={handleCreateAgent}
                  className="mt-4 bg-[#111] hover:bg-[#333] text-white px-6 py-2.5 rounded-xl text-sm font-medium transition-colors inline-flex items-center gap-2">
                  <FaPlus size={11} /> Create your first agent
                </button>
              )}
            </div>
          ) : (
            <div>
              {activeCategories.map(catKey => (
                <CategorySection
                  key={catKey}
                  categoryKey={catKey}
                  agents={grouped[catKey]}
                  telemetryData={telemetryData}
                  onDelete={handleDeleteClick}
                  onNavigate={agent => navigate(`/agents/${agent.id}/chat`, { state: { agent } })}
                />
              ))}
            </div>
          )}
        </div>

      </div>
    </>
  );
};

export default Agents;