name: Create Security Issue

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
      ref:
        required: true
        type: string
      actor:
        required: true
        type: string
      repository:
        required: true
        type: string
      run_id:
        required: true
        type: string
      server_url:
        required: true
        type: string
      issue_title:
        required: true
        type: string
      issue_body:
        required: true
        type: string
      issue_label:
        required: true
        type: string

    secrets:
      GH_TOKEN:
        required: true

jobs:
  create-issue:
    name: Create Security Issue
    runs-on: [dev-runner]
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get commit author GitHub username
        id: commit_author
        run: |
          GITHUB_USERNAME=$(gh api /repos/${{ inputs.repository }}/commits/${{ inputs.sha }} \
            --jq '.author.login // "${{ inputs.actor }}"')
          echo "username=$GITHUB_USERNAME" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Issue
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
         
          gh issue create \
              --title "${{ inputs.issue_title }}" \
              --body "${{ inputs.issue_body }}" \
              --label "${{ inputs.issue_label }}" \
              --assignee "${{ steps.commit_author.outputs.username }}"


              #test